spring.application.name=cdaxVideo
spring.datasource.url=jdbc:mysql://localhost:3306/cdaxx
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jackson.serialization.fail-on-empty-beans=false
server.port=8080

# Enable actuator endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# JWT Configuration
jwt.secret=+Qc2TsJKRR9nHIQKTYzp5B3JPzWOiZ7ief/Qgl+8yiEx6kp45IoOMdwKJBh3KDSit4KEgj2hsoXnvo1kBUw4Jw==
# JWT expiration time in seconds (24 hours)
jwt.expiration=86400
jwt.issuer=cdaxVideo